server:
  port: 8082
logging:
  level:
    com.tulingxueyuan.product: DEBUG
spring:
  application:
    name: product-service
  datasource:
    username: hc
    password: Hc_123456
    url: jdbc:mysql://139.199.175.93:3306/nacos?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 139.199.175.93:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
